### ISSUE TITLE
CUDA out of memory : Max memory and CPU running

### ISSUE THREAD

**Issue by remmel** [BoyanJIANG/LoRD#1]
Hi,

I want to run your code on my computer however it seems that I don't have enought VRAM on my GPU (running `python reconstruct.py lord --pcl_type depth_pcl --exp_name fit_depth_pcl --seq_name 00134_longlong_twist_trial2_21`).
**How much ram is required to run the demo?**

**How to run the demo on my CPU?**
Using `--g "-1"` doesn't seem to do anything (probably because torch is already initied at line `os.environ['CUDA_VISIBLE_DEVICES'] = args.g`)

I tried : 
- prefixing with `CUDA_VISIBLE_DEVICES=-1` : `CUDA_VISIBLE_DEVICES=-1 python reconstruct.py lord --pcl_type depth_pcl --exp_name fit_depth_pcl --seq_name 00134_longlong_twist_trial2_21`
- adding `map_location=torch.device('cpu')` inside  `load_dict = torch.load(` L32
- commenting L89 `os.environ['CUDA_VISIBLE_DEVICES'] = args.g`
but it leads to
```
  File "/home/remmel/workspace/LoRD/lib/reconstructor.py", line 197, in optimize_latent_code
    self.c_m = torch.randn(self.n_parts, self.latent_size).type(torch.cuda.FloatTensor) * self.init_std
RuntimeError: No CUDA GPUs are available
```

**Comment by BoyanJIANG** [comment]
Hi @remmel ,

Thanks for your interest in our work!

I tested the demo code on a single NVIDIA 2080Ti card with 11GB GPU memory. You can modify the value of `self.num_optim_samples` in L43 of `reconstructor.py` (it affects the number of points used in each optimization step) to reduce the memory cost.

You also can remove `.type(torch.cuda.FloatTensor)` (L197-198) for code initialization to run the demo on CPU. But this will lead to very slow running speed (40s per step).

**Comment by remmel** [comment]
Thanks, I'm able to go on
(`self.num_optim_samples = 6500` is ok on my laptop GTX 3060 6GB)
