### ISSUE TITLE
Reconstruction from Azure Kinect DK RGB-D

### ISSUE THREAD

**Issue by remmel** [BoyanJIANG/LoRD#2]
Hi,

I would like to reconstruct a 3D textured human from Kinect RGB-D sequence (Sec. 4.3 and Supp Mat 2.1).
But but how to start and convert my kinect ply (or texture jpg + "tum depth 16bit grayscale png") to .npz (needed by _cape_data_process.py_)?
Then you agree that I'll have to run the _reconstruct.py_ (depth_pcl) and _generate_mesh.py_ (fit_depth_pcl) ?

Thanks!

**Comment by BoyanJIANG** [comment]
Hi @remmel ,

`cape_data_process.py` is only for processing meshes from CAPE dataset, and I think there is no need to use it in your case.

You need to prepare point cloud sequence from the RGB-D captures and its SMPL fitting before running `reconstruct.py`. We provide sample codes in h4d_fitting.py to obtain SMPL fittings from point cloud sequences. Also, you can try other tools like [HuMoR](https://github.com/davrempe/humor), [FrankMocap](https://github.com/facebookresearch/frankmocap) or [rgbd-kinect-pose](https://github.com/rmbashirov/rgbd-kinect-pose) to do SMPL fitting.

**Comment by remmel** [comment]
Ok, thanks for the explanation
