### ISSUE TITLE
DynamicFusion Implementation

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [BoyanJIANG/LoRD#3]
Hi @BoyanJIANG, congrats on this great work and thanks a lot for open-sourcing this project! 

I noticed that you compare to DynamicFusion in the paper, e.g., Fig.6.(b). May I know whether you implement that yourself and whether you mind open-sourcing the corresponding code? Thanks a lot.

**Comment by BoyanJIANG** [comment]
Hi @Xiaoming-Zhao ,

Sorry for the late reply!
We use our own implementation of DynamicFusion, which is for internal use only for now. We hope to make it public in the future.

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for the information. Looking forward to the open-sourcing if it is possible.
