### ISSUE TITLE
Clothed human

### ISSUE THREAD

**Issue by remmel** [BoyanJIANG/LoRD#5]
Hi,

I successfull followed your steps to create  mesh from depth png image, but how to "cloth"/dress him like in your paper ? I mean having not a SMPL mesh, but something which match better the input ?
And next, do you released the texturing script part (also hidden part?)?

`data/demo/02474_longshort_ROM_lower_258/rendering/0000.png` (input; in my custom viewer; which looks clothed) :
<img width="194" alt="image" src="https://user-images.githubusercontent.com/937836/187763949-cb5ef675-25b2-4c09-8718-5275121799d5.png">

`dataset/02474_longshort_ROM_lower_258/h4d_fitting_refine/0000.ply` (which is nake / SMPL; generated by last command):
<img width="175" alt="image" src="https://user-images.githubusercontent.com/937836/187764039-7fb42043-62b9-493f-ad74-51ce6bf87165.png">

Thank you!

**Comment by BoyanJIANG** [comment]
Hi,

1. I add the last step for generating meshes from the optimized latent codes, sorry for missing that.
2. If the input point cloud (saved as .ply file) contains color information, you only need to add the `--texture` flag when running `reconstruct.py` and `generate_mesh.py` to produce the textured results.
