### ISSUE TITLE
Requirements update

### ISSUE THREAD

**Issue by remmel** [BoyanJIANG/LoRD#6]
Hi,

Here are some libraries which should be added in `requirements.txt`
- `chumpy` (thus https://github.com/BoyanJIANG/LoRD/tree/master/chumpy folder could be probably removed or is there differences?)
- `human_body_prior`

Note that `networkx==2.2` seems to not be compatible with python 3.9 [(`ImportError: cannot import name 'gcd' from 'fractions'`)](https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions); `networkx==2.8.6` can be used instead

Pytorch3d is also required

Also the following path https://github.com/BoyanJIANG/LoRD/blob/fa0a4a2347882217856c0ef5259b036349a4170c/lib/utils/h4d_utils.py#L87 references https://github.com/BoyanJIANG/H4D/blob/master/assets/pose_prior.pkl

Thanks!

**Comment by BoyanJIANG** [comment]
Hi @remmel,

Thanks a lot for reporting these!

About chumpy, it doesn't seem to support python 3, so I modify the setup.py to avoid errors when installing in a python 3 environment.

I removed the dependency on human_body_prior and added the `pose_prior.pkl` file in the `data` folder.

**Comment by remmel** [comment]
OK thanks for your quick answer! FYI, I do not have problem with chumpy 0.70 with my python 3.9 (and pip 22; checking the setup.py diff this was maybe more a problem related with old pip? - which python version do you use?)
